IGNOREABLE_WORDS = ["senior", "sr", "/", "&", "mission", "it", "and", "of", "mn", "in", "a"]
BAD_PHRASES = [
 'salesforce', 'salesforce developer', 'salesforce devops admin',
 'manager', 'engineering manager',
 'clearance required',
 'lead', 'lead software', 'lead software engineer',
 'analytics',
 'solution architect',
 'workflow design studio',
 'director',
]
GOOD_PHRASES = [
 'embedded',
 'go',
 'react',
 'web',
 'back end',
 'automation',
 'backend',
 'java',
 'hybrid',
 'python',
 'test',
 'remote',
 'iii',
 'reliability engineer', 'site reliability', 'site reliability engineer', 'site reliability engineering',
 'full stack',
 'developer',
 'full stack developer',
 'software', 'staff software', 'software developer', 'software development',
 'engineer', 'engineer iii', 'engineer ii', 'engineering',
 'devops engineer', 'network engineer', 'automation engineer', 'development engineer',
 'software engineer', 'software engineering', 'software engineer ii', 'software engineer iii',
 'embedded software engineer', 'software development engineer',
]
# all phrases from early set of liked/disliked jobs
PERTINENT_PHRASES = [
 'software development engineer',
 'full stack engineer',
 'embedded software engineer',
 'workflow design studio',
 'machine learning engineer',
 'full stack developer',
 'principal application engineer',
 'principal software engineer',
 'salesforce devops admin',
 'operations',
 'analytics',
 'embedded',
 'infrastructure',
 'solutions engineer',
 'solution',
 'react',
 'development engineer',
 'generative',
 'generative ai',
 'network engineer',
 'hybrid',
 'site reliability engineer',
 'software engineer ii',
 'eligible',
 'automation',
 'front',
 'machine learning',
 'machine',
 'test engineer',
 'design',
 'learning',
 'software developer',
 'reliability engineer',
 'platform engineer',
 'director',
 'network',
 'systems engineer',
 'site reliability',
 'site',
 'backend',
 'staff software engineer',
 'software engineer iii',
 'engineering manager',
 'staff software',
 'back end',
 'python',
 'quality engineering',
 'reliability',
 'development',
 'application engineer',
 'ai',
 'software engineering',
 'aws',
 'back',
 'java',
 'engineer iii',
 'salesforce',
 'solutions',
 'lead software engineer',
 'devops',
 'test',
 'lead software',
 'associate',
 'iii',
 'application',
 'quality',
 'platform',
 'engineer ii',
 'systems',
 'end',
 'ii',
 'remote',
 'data engineer',
 'cloud',
 'staff',
 'architect',
 'principal',
 'full stack',
 'full',
 'stack',
 'manager',
 'lead',
 'engineering',
 'developer',
 'data',
 'software engineer',
 'software',
 'engineer'
]
NEUTRAL_SKILLS = [
 'sql',
 'azure',
 'aws',
 'web',
 'etl', 
 'scripting',
 'databases',
 'devops',
 'database',
 'saas', 
 'crm', 
 'css', 
 '.net', 
 'algorithms', 
 'c#', 
 'html', 
 'sre', 
 's3', 
 'qa', 
 'ip', 
 'tableau', 
 'r', 
 'matlab', 
 'elt', 
 'xml', 
 'jira', 
 'powershell', 
]
BAD_SKILLS = [
 'salesforce',
 'servicenow',
 'ad', 
 'sap', 
]
GOOD_SKILLS = [
 'javascript',
 'java',
 'python',
 'c++', 
 'react',
 'linux',
 'docker',
 'kubernetes',
 'orchestration', 
 'go',
 'scale',
 'jenkins', 
 'nosql', 
 'scalability', 
 'angular', 
 'backend', 
 'embedded', 
 'git', 
 'container', 
 'terraform', 
 'typescript', 
 'rest', 
 'c', 
 'spring', 
 'node.js', 
 'android', 
 'scala', 
 'mysql', 
 'apache', 
 'ruby', 
 'frontend', 
 'oracle', 
 'github', 
 'bash', 
 'microservices', 
 'shell', 
 'mongodb', 
 'postgres', 
 'node', 
 'postgresql', 
 'fpga', 
 'unix', 
 'rdbms',
 'selenium', 
 'containerization',
 'gitlab', 
 'dynamodb', 
 'firmware', 
 'kotlin', 
 'json', 
 'restful', 
 'datadog', 
 'lambda', 
 'kafka', 
 'ansible', 
]
SKILLS = set(GOOD_SKILLS + NEUTRAL_SKILLS + BAD_SKILLS)